// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: links.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (id, created_at, expire_at, url)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, expire_at, url
`

type CreateLinkParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	ExpireAt  time.Time
	Url       string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink,
		arg.ID,
		arg.CreatedAt,
		arg.ExpireAt,
		arg.Url,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpireAt,
		&i.Url,
	)
	return i, err
}
