---
linters:
  enable-all: true
  disable:
    # Deprecated
    - deadcode
    - ifshort
    - scopelint
    - maligned
    - golint
    - varcheck
    - nosnakecase
    - structcheck
    - interfacer
    - exhaustivestruct
    # Conflicts with gofmt
    - wsl
    # I do like some empty structs
    - exhaustruct
    # Although useful, sometimes I need to return with errors before ending the functions
    - wrapcheck

linters-settings:
  # Packages allowed
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitly denied
        files:
          - $all
          - $test
        allow:
          - $gostd
          - github.com/redds-be/rlinks/database
          - github.com/lib/pq
          - github.com/mattn/go-sqlite3
          - github.com/google/uuid
          - github.com/joho/godotenv
          - github.com/dchest/uniuri
          - github.com/alexedwards/argon2id
          - github.com/stretchr/testify/suite
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  # Default values conflicts with gofmt
  lll:
    line-length: 160
    tab-width: 1