services:
  postgresql:
    image: postgres:17-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${REDDLINKS_DB_PASSWORD:?database password required}
      POSTGRES_USER: ${REDDLINKS_DB_USERNAME:-rluser}
      POSTGRES_DB: ${REDDLINKS_DB_NAME:-rldb}
    env_file:
      - .env
  reddlinks:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    environment:
      REDDLINKS_DB_HOST: ${REDDLINKS_DB_HOST:-postgresql}
      REDDLINKS_DB_PORT: ${REDDLINKS_DB_PORT:-5432}
      REDDLINKS_DB_TYPE: ${REDDLINKS_DB_TYPE:-postgres}
      REDDLINKS_DB_PASSWORD: ${REDDLINKS_DB_PASSWORD:?database password required}
      REDDLINKS_DB_USERNAME: ${REDDLINKS_DB_USERNAME:-rluser}
      REDDLINKS_DB_NAME: ${REDDLINKS_DB_NAME:-rldb}
      REDDLINKS_INSTANCE_URL: ${REDDLINKS_INSTANCE_URL:?instance url (public FQDN) required}
    env_file:
      - .env
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    user: "1000:1000"

volumes:
  db:
    driver: local
