FROM golang:1.21-alpine3.19

RUN apk update && apk add --no-cache build-base git

EXPOSE 8080

RUN mkdir /opt/reddlinks
ADD . /opt/reddlinks
WORKDIR /opt/reddlinks
RUN go get github.com/redds-be/reddlinks

RUN go build
RUN mv reddlinks /usr/local/bin/

ENTRYPOINT ["reddlinks"]