name: docker-build

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build --build-arg tag_version=$GITHUB_REF_NAME -t reddlinks -f docker/Dockerfile .
