name: gotest

on: [push]

permissions:
  contents: read

jobs:
  gotest:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false
      - name: Test the project
        run: |
          go test ./...
